<?php
declare(strict_types=1);

function getCatalogo(): array {
    return [
        'growth' => [
            'nombre' => 'Plan Growth',
            'precio' => '$349.990/mes',
            'tipo' => 'mensual',
            'incluye' => [
                'Mantenimiento web continuo (sitio actualizado, seguro y funcionando)',
                'Hosting + SSL incluido permanentemente',
                'Soporte técnico (respuesta en menos de 24 horas)',
                '2 cambios menores al mes en sitio web (textos, imágenes, ajustes)',
                'Gestión de Ads en 1 plataforma (Google Ads o Meta Ads) con optimización continua',
                'Configuración de tracking (GTM + GA4 + Pixel según plataforma)',
                'Automatización de leads (email bienvenida, formularios inteligentes, secuencias automáticas)',
                'Dashboard personalizado con métricas: inversión, leads, costo por cliente',
                'Hasta 4 cambios de anuncios o creatividades por mes',
                'Hasta 2 ajustes al dashboard por mes',
                '1 reporte mensual de rendimiento',
            ],
            'no_incluye' => [
                'Producción de material audiovisual (fotos, videos, diseño gráfico)',
                'Gestión en segunda plataforma de ads',
                'Inversión publicitaria (presupuesto de ads)',
                'SEO orgánico',
                'Gestión de redes sociales orgánicas (publicaciones, community management)',
            ],
            'herramientas' => ['Google Ads o Meta Ads (cuenta del cliente)', 'Google Tag Manager', 'Google Analytics 4', 'Meta Pixel / API de Conversiones', 'Dashboard Facand (hosting incluido)'],
            'responsabilidades' => [
                'Entregar material audiovisual para creatividades (fotos, videos, testimonios)',
                'Proveer accesos a cuentas publicitarias y plataformas',
                'Aprobar creatividades y textos de anuncios cuando se solicite',
                'Informar cambios de oferta, promociones o temporadas con 5 días de anticipación',
                'Reportar cambios web con al menos 3 días hábiles de anticipación',
            ],
        ],
        'scale' => [
            'nombre' => 'Plan Scale',
            'precio' => '$749.990/mes',
            'tipo' => 'mensual',
            'incluye' => [
                'Todo lo del Plan Growth (mantenimiento, ads, automatización, reportes)',
                'Ads omnicanal (Google + Meta) con remarketing cruzado y optimización conjunta',
                'Dashboard personalizado a medida del negocio',
                'Agente IA (bot conversacional que atiende y califica leads 24/7)',
                'Automatizaciones avanzadas (workflows personalizados, integraciones con sistemas)',
                'Reunión estratégica semanal con el equipo',
                'Hasta 4 cambios de anuncios + 4 cambios de creatividades por mes',
                'Hasta 4 ajustes al dashboard por mes',
                'Reporte mensual unificado',
            ],
            'no_incluye' => [
                'Producción de material audiovisual',
                'Inversión publicitaria',
                'Desarrollo de software a medida',
            ],
            'herramientas' => ['Google Ads + Meta Ads (cuentas del cliente)', 'GTM + GA4 + Meta Pixel + API de Conversiones', 'Dashboard Facand personalizado', 'Agente IA Facand'],
            'responsabilidades' => [
                'Entregar material audiovisual',
                'Proveer accesos a todas las plataformas',
                'Asistir a reuniones estratégicas semanales',
                'Compartir información del negocio para entrenar al agente IA',
            ],
        ],
        'starter' => [
            'nombre' => 'Plan Starter',
            'precio' => '$99.990/mes',
            'tipo' => 'mensual',
            'incluye' => [
                'Mantenimiento web continuo (sitio actualizado, seguro y funcionando)',
                'Hosting + SSL incluido permanentemente',
                'Soporte técnico (respuesta en menos de 24 horas)',
                '2 cambios menores al mes (textos, imágenes, ajustes visuales)',
                'Backup mensual del sitio',
                'Actualizaciones de seguridad',
            ],
            'no_incluye' => [
                'Desarrollo de nuevas secciones o funcionalidades',
                'Rediseño parcial o total',
                'Gestión de campañas publicitarias',
                'SEO orgánico',
                'Copywriting',
            ],
            'herramientas' => ['Hosting Facand', 'SSL incluido'],
            'responsabilidades' => [
                'Reportar cambios con al menos 3 días hábiles de anticipación',
                'Proveer contenido actualizado (textos, imágenes)',
            ],
        ],
        'meta_ads' => [
            'nombre' => 'Meta Ads',
            'precio' => '$179.990/mes',
            'tipo' => 'mensual',
            'incluye' => [
                'Segmentación avanzada por intereses, comportamiento y ubicación',
                'Diseño de creativos para Feed, Stories y Reels (con material provisto por el cliente)',
                'Instalación y configuración de Meta Pixel + API de Conversiones',
                'Gestión de presupuesto optimizado (menor CPC posible)',
                'Optimización semanal',
                'Hasta 4 cambios de creatividades por mes',
                '1 reporte mensual de rendimiento',
                'Dashboard personalizado con métricas en tiempo real',
                'Hasta 2 ajustes al dashboard por mes',
            ],
            'no_incluye' => [
                'Producción de material audiovisual (videos, fotos, diseño gráfico)',
                'Gestión de redes sociales orgánicas',
                'Inversión publicitaria',
                'Gestión de WhatsApp Business API',
            ],
            'herramientas' => ['Meta Business Suite / Ads Manager', 'Meta Pixel', 'API de Conversiones', 'Dashboard Facand'],
            'responsabilidades' => [
                'Proveer acceso de administrador a página de Facebook y cuenta publicitaria',
                'Entregar material audiovisual para creatividades',
                'Aprobar creatividades cuando se solicite',
                'Informar promociones o cambios de oferta con 5 días de anticipación',
            ],
        ],
        'google_ads' => [
            'nombre' => 'Google Ads',
            'precio' => '$179.990/mes',
            'tipo' => 'mensual',
            'incluye' => [
                'Posicionamiento en los primeros resultados de Google',
                'Investigación de keywords estratégicas con intención de compra',
                'Redacción de anuncios persuasivos con CTAs claros',
                'Configuración de conversiones y seguimiento',
                'Instalación y configuración de Google Tag Manager (GTM) + Google Analytics 4 (GA4)',
                'Creación de audiencias en GA4 para remarketing',
                'Optimización semanal: pujas, keywords negativas, tests',
                'Hasta 4 cambios de anuncios por mes',
                '1 reporte mensual de rendimiento',
                'Dashboard personalizado con métricas en tiempo real',
                'Hasta 2 ajustes al dashboard por mes',
            ],
            'no_incluye' => [
                'Producción de material audiovisual o gráfico',
                'Desarrollo o modificación de landing pages',
                'Inversión publicitaria',
                'Gestión de Google My Business / Google Maps',
                'SEO orgánico',
            ],
            'herramientas' => ['Google Ads', 'Google Tag Manager', 'Google Analytics 4', 'Dashboard Facand'],
            'responsabilidades' => [
                'Proveer acceso a cuenta de Google Ads',
                'Aprobar textos de anuncios cuando se solicite',
                'Proveer información del negocio: servicios, precios, diferenciadores',
                'Entregar material visual para campañas Display o PMax',
            ],
        ],
        'full_ads' => [
            'nombre' => 'Full Ads',
            'precio' => '$299.990/mes',
            'tipo' => 'mensual',
            'incluye' => [
                'Omnipresencia digital: Meta Ads + Google Ads combinados',
                'Sinergia de datos entre plataformas para optimizar embudo completo',
                'Remarketing cruzado (Google → Instagram, Instagram → Google)',
                'Hasta 4 cambios de anuncios + 4 cambios de creatividades por mes',
                '1 reporte mensual unificado (rendimiento comparativo por plataforma)',
                'Dashboard personalizado unificado',
                'Hasta 2 ajustes al dashboard por mes',
            ],
            'no_incluye' => [
                'Producción de material audiovisual',
                'Landing pages',
                'Inversión publicitaria',
                'SEO orgánico',
                'Gestión de redes orgánicas',
            ],
            'herramientas' => ['Google Ads + Meta Ads', 'GTM + GA4 + Meta Pixel + API de Conversiones', 'Dashboard Facand unificado'],
            'responsabilidades' => [
                'Proveer accesos a ambas plataformas',
                'Entregar material audiovisual',
                'Aprobar creatividades y textos de anuncios',
                'Informar cambios de oferta con 5 días de anticipación',
            ],
        ],
        'full_ads_seo' => [
            'nombre' => 'Full Ads + SEO',
            'precio' => '$399.990/mes',
            'tipo' => 'mensual',
            'incluye' => [
                'Todo lo del plan Full Ads (Meta + Google + remarketing cruzado)',
                'SEO orgánico mensual: contenido, backlinks, velocidad, estructura',
                'Estrategia de contenido para búsquedas clave de la industria',
                'Hasta 4 optimizaciones de páginas por mes (SEO on-page)',
                'Reporte integral: pagado + orgánico en un solo dashboard',
            ],
            'no_incluye' => [
                'Redacción de contenido extenso (blog, artículos)',
                'Link building masivo',
                'SEO local (Google My Business)',
                'Garantía de posiciones específicas en Google',
            ],
            'herramientas' => ['Todo lo de Full Ads', 'Google Search Console'],
            'responsabilidades' => [
                'Todo lo de Full Ads',
                'Proveer acceso a Google Search Console',
                'Implementar recomendaciones de contenido cuando aplique',
            ],
        ],
    ];
}

function getClientesPlanMap(): array {
    return [
        'novavita' => ['plan' => 'growth', 'precio_custom' => null],
        'legalfam' => ['plan' => 'growth', 'precio_custom' => '$100.000/mes (hasta abril) → $349.990/mes (desde mayo)'],
        'dra-irisvera' => ['plan' => 'growth', 'precio_custom' => '$349.990/mes (desde mayo 2026)'],
        'maz' => ['plan' => null, 'precio_custom' => '$0 (negocio propio)'],
        'legacy' => ['plan' => 'google_ads', 'precio_custom' => '$250.000/mes (incluye Google Ads + sitio web)'],
        'ansar' => ['plan' => 'google_ads', 'precio_custom' => '$200.000/mes (desde mayo 2026)'],
        'resalta' => ['plan' => 'full_ads', 'precio_custom' => '$150.000/mes (desde mayo 2026)'],
        'prime' => ['plan' => 'full_ads', 'precio_custom' => '$140.000/mes'],
        'vuela-barato' => ['plan' => 'meta_ads', 'precio_custom' => '$150.000/mes'],
        'jojay' => ['plan' => 'full_ads', 'precio_custom' => '$25.000/mes (abr-dic 2026)'],
        'ecoloo' => ['plan' => 'google_ads', 'precio_custom' => '$25.000/mes (abr-dic 2026)'],
        'rapid-transfer' => ['plan' => null, 'precio_custom' => '$30.000/mes (subcuenta GHL)'],
        'terra-activos' => ['plan' => null, 'precio_custom' => '$16.990 + IVA/mes (plan legacy)'],
        'siria-lopez' => ['plan' => null, 'precio_custom' => 'Canje (sin costo monetario)'],
        'nuba' => ['plan' => null, 'precio_custom' => 'Pendiente (transición)'],
        'asfae' => ['plan' => null, 'precio_custom' => '$1.190.000 (abr) + $175.000/mes (may-nov)'],
        'awa' => ['plan' => 'google_ads', 'precio_custom' => '$100.000/mes (Google Ads + sitio web)'],
    ];
}
